/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js";
import PrivatePaymentContractArtifactJson from "../../contract/target/contract-PrivatePayment.json" with { type: "json" };
export const PrivatePaymentContractArtifact = loadContractArtifact(
  PrivatePaymentContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract PrivatePayment;
 */
export class PrivatePaymentContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, PrivatePaymentContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(
      address,
      PrivatePaymentContract.artifact,
      wallet,
    ) as Promise<PrivatePaymentContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(
    wallet: Wallet,
    token_address: AztecAddressLike,
    token_amount: bigint | number,
  ) {
    return new DeployMethod<PrivatePaymentContract>(
      PublicKeys.default(),
      wallet,
      PrivatePaymentContractArtifact,
      PrivatePaymentContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    token_address: AztecAddressLike,
    token_amount: bigint | number,
  ) {
    return new DeployMethod<PrivatePaymentContract>(
      publicKeys,
      wallet,
      PrivatePaymentContractArtifact,
      PrivatePaymentContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<
    M extends keyof PrivatePaymentContract["methods"],
  >(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PrivatePaymentContract["methods"][M]>
  ) {
    return new DeployMethod<PrivatePaymentContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PrivatePaymentContractArtifact,
      PrivatePaymentContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PrivatePaymentContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      PrivatePaymentContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    "token_address" | "token_amount" | "commitment"
  > {
    return {
      token_address: {
        slot: new Fr(1n),
      },
      token_amount: {
        slot: new Fr(2n),
      },
      commitment: {
        slot: new Fr(3n),
      },
    } as ContractStorageLayout<"token_address" | "token_amount" | "commitment">;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** complete_order(_nonce: field) */
    complete_order: ((_nonce: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(token_address: struct, token_amount: integer) */
    constructor: ((
      token_address: AztecAddressLike,
      token_amount: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
